In [30]:
import pandas as pd

mydata = pd.read_csv('requirements/emailClassify.csv',sep='\t',header=None,names=['output','message'])
print(mydata)

   output                                            message
0    mail  Hi Simran, can we reschedule our meeting to to...
1    mail  Please find the attached report for this week'...
2    mail     Don't forget our team lunch on Friday at 1 PM.
3    spam  Congratulations! You have won a ₹50,000 cash p...
4    mail  Could you review the pull request before the e...
5    mail  The interview has been scheduled for Monday at...
6    mail  Thank you for your application. We will get ba...
7    mail  The client appreciated your presentation. Grea...
8    spam  Exclusive offer! Get 90% off on all products. ...
9    mail  Can you share the latest project documentation...
10   mail  The database backup completed successfully wit...
11   mail  Let's catch up over coffee next week if you're...
12   mail  Your order has been shipped and is expected to...
13   spam  Urgent! Your bank account will be suspended un...
14   mail  The weekly sprint planning meeting has been mo...
15   mail  Please approv

In [31]:
# Data Cleaning and Preprocessing
import nltk
from nltk.corpus import stopwords
import re

lemm = nltk.stem.WordNetLemmatizer()
stopwords = set(stopwords.words('english'))
corpus = []

for i in range(len(mydata)):
    #remove special characters and digits
    msg = re.sub(r'[^a-zA-Z]',' ',mydata['message'][i])

    #convert to lowercase
    msg=msg.lower()

    #tokenization
    msg = nltk.word_tokenize(msg)

    #lemmatize and remove stop words
    msg = [lemm.lemmatize(word, pos='v') for word in msg if word not in stopwords]
    msg = ' '.join(msg)

    #add messages to corpus
    corpus.append(msg)

print(corpus)


['hi simran reschedule meet tomorrow pm', 'please find attach report week sales analysis', 'forget team lunch friday pm', 'congratulations cash prize click claim', 'could review pull request end day', 'interview schedule monday', 'thank application get back soon', 'client appreciate presentation great work', 'exclusive offer get products limit time', 'share latest project documentation team', 'database backup complete successfully without errors', 'let catch coffee next week available', 'order ship expect arrive thursday', 'urgent bank account suspend unless update kyc today', 'weekly sprint plan meet move', 'please approve leave request submit rahul', 'password change successfully action require', 'lucky winner spin wheel collect reward', 'conference room book client presentation', 'act earn per day work home experience']


## BOW

In [32]:
# Bag of Words Model to convet text to feature vectors
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(max_features=100)
# cv = CountVectorizer(max_features=100, binary=True) --> for binary features
X = cv.fit_transform(corpus).toarray()

print(X)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 1]]


## BOW with N-gram

In [33]:
cv = CountVectorizer(max_features=300, ngram_range=(1,2)) # range=(2,3) for bigrams and trigrams
X = cv.fit_transform(corpus).toarray()

cv.vocabulary_  # to see the features generated by the model

{'hi': np.int64(77),
 'simran': np.int64(150),
 'reschedule': np.int64(135),
 'meet': np.int64(97),
 'tomorrow': np.int64(171),
 'pm': np.int64(117),
 'hi simran': np.int64(78),
 'simran reschedule': np.int64(151),
 'reschedule meet': np.int64(136),
 'meet tomorrow': np.int64(99),
 'tomorrow pm': np.int64(172),
 'please': np.int64(114),
 'find': np.int64(66),
 'attach': np.int64(15),
 'report': np.int64(129),
 'week': np.int64(179),
 'sales': np.int64(142),
 'analysis': np.int64(6),
 'please find': np.int64(116),
 'find attach': np.int64(67),
 'attach report': np.int64(16),
 'report week': np.int64(130),
 'week sales': np.int64(181),
 'sales analysis': np.int64(143),
 'forget': np.int64(68),
 'team': np.int64(164),
 'lunch': np.int64(95),
 'friday': np.int64(70),
 'forget team': np.int64(69),
 'team lunch': np.int64(165),
 'lunch friday': np.int64(96),
 'friday pm': np.int64(71),
 'congratulations': np.int64(46),
 'cash': np.int64(26),
 'prize': np.int64(120),
 'click': np.int64(33),
 

## TF-IDF

In [34]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(max_features=100)  # Here you can also use ngram_range=(1,2) for bigrams and trigrams
X = tfidf.fit_transform(corpus).toarray()

print(X)

[[0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.40824829 0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.39087152 0.         ... 0.         0.         0.34358205]]
